version: '3'
services:
  app:
    container_name: joker
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'